import { OnInit, AfterViewChecked } from '@angular/core';
export declare class NgxWheelComponent implements OnInit, AfterViewChecked {
    colors: Array<string>;
    prizeToWin: string;
    prize_descriptions: Array<string>;
    constructor();
    ngOnInit(): void;
    ngAfterViewChecked(): void;
    arcDeg: any;
    startAngle: any;
    arc: any;
    angleNeeded: any;
    spins: any;
    angleToBeSpun: any;
    spinTimeout: any;
    spinArcStart: any;
    spinTime: any;
    spinTimeTotal: any;
    current_user_status: any;
    spin_results: any;
    ctx: any;
    spinAngleStart: number;
    spun: boolean;
    init(): void;
    getAngleNeeded(prize: any): number;
    drawSpinnerWheel(): void;
    spin(): void;
    easeOut(t: any, b: any, c: any, d: any): any;
    rotateWheel(): void;
    stopRotateWheel(): void;
    clicked(): void;
}
